### ISSUE TITLE
Credentialed Response returning "True" mismatch with "true"

### ISSUE THREAD

**Issue by jmcc7** [frame-cors/frame-cors#2]
when setting "allow-credentials": true, getting error: 

Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is 'True'. It must be 'true' to allow credentials.

In ControllerHandler, line 85, bools converted via ToString() which returns "True" rather than "true". Was able to use ToString().ToLower() and it seems to be working fine. Sorry didn't have time to set up a pull but will try to get there.

**Comment by gptankit** [comment]
Thanks Joseph. The fix is done in the latest commit.

**Comment by gptankit** [comment]
Also, published Frame.Cors v0.2.1 to nuget.
